#!/bin/sh

mock -r fedora-41-x86_64 \
    --spec ./ollama.spec --sources $(pwd)/SOURCES \
    --addrepo https://raw.githubusercontent.com/fachep/ollama-rpm/refs/heads/repo/repo \
    --without rocm \
    --enable-plugin ccache --enable-network $@