#!/bin/sh

mock -r fedora-41-x86_64 \
    --rebuild ./SRPMS/ollama-0.5.9-1.fc41.src.rpm \
    --addrepo https://raw.githubusercontent.com/fachep/ollama-rpm/refs/heads/repo/repo \
    --without rocm \
    --enable-plugin ccache --enable-network $@