name: Sync dependencies from rawhide source

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch_deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: repo

      - name: Clean up
        run: rm -rf repo

      - name: Download Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y dnf dnf-plugins-core
          sudo mkdir -p /etc/yum.repos.d
          echo -e "[rawhide]\nname=Rawhide\nbaseurl=https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os/" | sudo tee /etc/yum.repos.d/rawhide.repo
          mkdir -p repo
          cd repo
          for file in $(cat ../whitelist.txt); do
            dnf download $file --repo=rawhide --releasever=rawhide
          done
          ls *.rpm | sort > ../files.txt
          cd ..
      
      - name: Check for changes
        run: |
          if git diff --quiet files.txt; then
            echo "No changes"
            exit 0
          fi
    
      - name: Commit changes
        run: |
          sudo apt-get install -y createrepo-c
          createrepo_c repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          echo Sync `date` > commit_message
          git diff HEAD -- files.txt | grep '^+[^+]' >> commit_message
          git commit -F commit_message
          git pull --rebase "origin" "repo"
          git push